name: Daily Commodity Data Refresh

on:
  schedule:
    # Run at midnight UTC every day (00:00)
    - cron: '0 0 * * *'
  workflow_dispatch:  # Allow manual triggering for testing

jobs:
  refresh-data:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Set up Conda
      uses: conda-incubator/setup-miniconda@v3
      with:
        auto-update-conda: true
        python-version: '3.11'
        environment-file: false
        
    - name: Create and activate conda environment
      run: |
        conda create -n commodity-price-forecasting python=3.11 -y
        conda activate commodity-price-forecasting
      shell: bash -l {0}
      
    - name: Install dependencies
      run: |
        conda activate commodity-price-forecasting
        pip install -r requirements.txt
      shell: bash -l {0}
      
    - name: Run daily data refresh
      run: |
        conda activate commodity-price-forecasting
        python -m tasks.daily_data_refresh
      shell: bash -l {0}
      
    - name: Check if database was updated
      run: |
        if [ -f "commodities.db" ]; then
          echo "Database file exists and was updated"
          ls -la commodities.db
        else
          echo "Warning: Database file not found"
          exit 1
        fi
      shell: bash
      
    - name: Commit and push updated database
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add commodities.db
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m "Daily data refresh: $(date '+%Y-%m-%d %H:%M:%S UTC')"
          git push
        fi
      shell: bash
      
    - name: Upload database as artifact (backup)
      uses: actions/upload-artifact@v4
      if: success()
      with:
        name: commodities-db-${{ github.run_number }}
        path: commodities.db
        retention-days: 7 